
# Networks ############################################################################################################

networks:
  cardano:
    name: cardano
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

# Services ############################################################################################################

services:

  # Block Producer ----------------------------------------------------------------------------------------------------

  bprod:
    image: nessusio/cardano-node:${CARDANO_NODE_VERSION:-latest}
    container_name: bprod
    restart: ${CARDANO_RESTART_POLICY:-always}
    hostname: bprod
    networks:
      cardano:
    ports:
      - "3001:3001"
    environment:
      CARDANO_TOPOLOGY: '{
          "Producers": [
            {
              "addr": "relay01.astorpool.net",
              "port": ${CARDANO_RELAY01_PORT:-3001},
              "valency": 1
            },
            {
              "addr": "relay02.astorpool.net",
              "port": ${CARDANO_RELAY02_PORT:-3001},
              "valency": 1
            },
            {
              "addr": "relay03.astorpool.net",
              "port": ${CARDANO_RELAY03_PORT:-3001},
              "valency": 1
            }
          ]
        }'
      CARDANO_RTS_OPTS: "${CARDANO_RTS_OPTS:--N -A64m -c -s}"
      CARDANO_BLOCK_PRODUCER: "${CARDANO_BLOCK_PRODUCER:-true}"
    command: "run"
    volumes:
      - mainnet-bprod-keys:/var/cardano/config/keys
      - ${CARDANO_NODE_DATA:-node-data}:/opt/cardano/data
      - node-ipc:/opt/cardano/ipc

  # NGINX -------------------------------------------------------------------------------------------------------------

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    hostname: nginx
    networks:
      cardano:
    ports:
      - "12798:80"
    volumes:
      - nginx-config:/etc/nginx:ro

# Volumes #############################################################################################################

volumes:
  mainnet-bprod-keys:
    external: true
  node-data:
    external: true
  node-ipc:
    external: true
  nginx-config:
    external: true
